### PR TITLE
The project on React is created

### PR DESCRIPTION
**Pull request by MetalMari**

### CODE REVIEW

**Comment by dmytrosmetanin** [comment]
App created

**Review by dmytrosmetanin — APPROVED** [review]
Approved.

**Review by dmytrosmetanin — APPROVED** [review]
Approved.

**Review by Viktorika-p — APPROVED** [review]

**Comment by MetalMari** [comment]
Accidentally the branch was removed and reopened

**Review by MrSancho42 — APPROVED** [review]

**Pull request merged**
